import React, { useMemo, useState } from 'react';
import { useApp, MeuViverMaisTab } from '../context/AppContext';
import { DIMENSIONS } from '../mock/dimensions';
import { formatPercentage } from '../utils/formatters';
import { AssessmentRecord, DimensionId, PDPAction } from '../types';
import { DEMO_FINANCIAL_COMPOSITION, DEMO_GDP_HISTORY, DEMO_HEALTH_INDICATORS, DEMO_REFERENCE_GROUP, GdpHistoryPoint, MIN_COHORT_SIZE } from '../mock/gdpDemoData';
import { Activity, ArrowRight, BarChart3, Calendar, CheckCircle2, ChevronDown, CircleHelp, HeartPulse, History, Info, LineChart as LineIcon, Plus, ShieldCheck, Sparkles, Target, Users, X } from 'lucide-react';
import { Area, Bar, CartesianGrid, Cell, ComposedChart, Line, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

const card = 'bg-white rounded-3xl border border-[#D9E4EE] shadow-sm';
const date = (value?: string) => value ? new Date(value).toLocaleDateString('pt-BR') : '—';
const scoreOf = (record: AssessmentRecord | null | undefined, id: DimensionId, fallback: number) => record?.axisResults.find((axis) => axis.axisId === id)?.score ?? fallback;
const labelFor = (id: DimensionId) => DIMENSIONS.find((item) => item.id === id)?.name ?? id;
const statusFor = (value: number, median: number, p25: number, p75: number) => value > p75 ? 'Acima da faixa mais frequente' : value < p25 ? 'Oportunidade de atenção' : Math.abs(value - median) <= 5 ? 'Dentro da faixa de referência' : 'Dimensão para acompanhar';

const DEMO_ACTIONS: PDPAction[] = DEMO_GDP_HISTORY.flatMap((point) => point.actionsStarted.map((title, index) => ({ id: `${point.id}-action-${index}`, participantId: 'carlos', assessmentId: point.id, pillarId: point.opportunities[0] === 'Saúde emocional' ? 'saude_emocional' : 'recursos_financeiros', title, description: 'Ação demonstrativa registrada entre avaliações.', status: point.year === 2026 ? 'em_andamento' : 'concluida', progress: point.year === 2026 ? 40 : 100, createdAt: point.date, updatedAt: point.date })));

const Pill = ({ children, tone = 'teal' }: { children: React.ReactNode; tone?: 'teal' | 'blue' | 'gold' }) => <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-bold ${tone === 'gold' ? 'bg-[#FFF7DF] text-[#7C641E]' : tone === 'blue' ? 'bg-[#EBF3FA] text-[#164E7A]' : 'bg-[#E6F7F6] text-[#0A7D76]'}`}>{children}</span>;

const EmptyState = ({ children }: { children: React.ReactNode }) => <div className="rounded-2xl border border-dashed border-[#B9CAD8] bg-[#F8FAFC] p-5 text-sm text-[#5A6F82]">{children}</div>;

export const MeuViverMaisView: React.FC = () => {
  const { currentParticipant, surveyResult, surveyHistory, meuViverMaisTab, setMeuViverMaisTab, navigateTo, myPlan } = useApp();
  const [showDemo, setShowDemo] = useState(false);
  const [period, setPeriod] = useState<'1' | '3' | '5' | 'all'>('5');
  const [selectedPillar, setSelectedPillar] = useState<'ibpl' | DimensionId>('ibpl');
  const [selectedPoint, setSelectedPoint] = useState<GdpHistoryPoint | null>(null);
  const [comparisonView, setComparisonView] = useState<'participant' | 'cohort' | 'community'>('participant');
  const [healthOpen, setHealthOpen] = useState(false);

  const realCount = surveyHistory.length;
  const latestReal = surveyResult ? surveyHistory[0] : null;
  const isDemonstrative = showDemo || realCount === 0;
  const currentScore = surveyResult?.ibplScore ?? (currentParticipant.id === 'carlos' ? 60 : currentParticipant.ibpl);
  const currentPillarScores = useMemo(() => DIMENSIONS.reduce((acc, item) => { acc[item.id] = surveyResult ? scoreOf(latestReal, item.id, currentParticipant.scores[item.id]) : currentParticipant.scores[item.id]; return acc; }, {} as Record<DimensionId, number>), [currentParticipant.scores, latestReal, surveyResult]);
  const chartHistory = useMemo(() => {
    if (!showDemo && realCount >= 2) return surveyHistory.slice(0, period === '1' ? 2 : period === '3' ? 4 : surveyHistory.length).reverse().map((record) => ({ id: record.id, year: new Date(record.assessmentDate).getFullYear(), date: record.assessmentDate, personal: record.ibplScore ?? 0, median: undefined, p25: undefined, p75: undefined, pillarScores: Object.fromEntries(DIMENSIONS.map((item) => [item.id, scoreOf(record, item.id, currentParticipant.scores[item.id])])) as Partial<Record<DimensionId, number>>, strengths: record.strengths, opportunities: record.priorityOpportunities, actionsStarted: [], actionsCompleted: [], programs: [], lifeMoments: record.lifeMoments, notes: record.context }));
    const amount = period === '1' ? 1 : period === '3' ? 3 : period === '5' ? 5 : DEMO_GDP_HISTORY.length;
    return DEMO_GDP_HISTORY.slice(-amount);
  }, [currentParticipant.scores, period, realCount, showDemo, surveyHistory]);
  const chartData = chartHistory.map((point) => ({ ...point, value: selectedPillar === 'ibpl' ? point.personal : point.pillarScores[selectedPillar] ?? 0, pillarMedian: selectedPillar === 'ibpl' ? point.median : undefined }));
  const latestPoint = chartHistory[chartHistory.length - 1];
  const referenceAvailable = DEMO_REFERENCE_GROUP.participantCount >= MIN_COHORT_SIZE;
  const groupText = `Sua referência considera participantes de ${DEMO_REFERENCE_GROUP.ageRange}, em fase de aposentadoria semelhante e com características disponíveis próximas ao seu contexto.`;

  const tabs: { id: MeuViverMaisTab; label: string; icon: React.ReactNode }[] = [{ id: 'visao_geral', label: 'Visão geral', icon: <Activity className="w-4 h-4" /> }, { id: 'gdp', label: 'Meu Retrato e Evolução', icon: <History className="w-4 h-4" /> }, { id: 'pdp', label: 'Meu PDP', icon: <Target className="w-4 h-4" /> }];
  return <div className="mx-auto max-w-7xl space-y-6 px-4 py-8 lg:px-8">
    <section className={`${card} space-y-5 p-6 sm:p-8`}><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><span className="text-xs font-black uppercase tracking-widest text-[#0A7D76]">Área pessoal</span><h1 className="mt-1 text-2xl font-black text-[#163A63] sm:text-3xl">Meu Viver Mais</h1><p className="mt-1 text-sm text-[#5A6F82]">Acompanhe seu momento, suas escolhas e sua evolução.</p></div>{!surveyResult && <button onClick={() => navigateTo('questionario_intro')} className="rounded-xl bg-[#163A63] px-4 py-3 text-sm font-bold text-white">Começar meu GDP <ArrowRight className="inline h-4 w-4" /></button>}</div><nav aria-label="Navegação do Meu Viver Mais" className="flex gap-2 overflow-x-auto border-b border-[#EEF3F7] pb-2">{tabs.map((tab) => <button key={tab.id} onClick={() => setMeuViverMaisTab(tab.id)} aria-current={meuViverMaisTab === tab.id ? 'page' : undefined} className={`flex shrink-0 items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold ${meuViverMaisTab === tab.id ? 'bg-[#163A63] text-white' : 'text-[#5A6F82] hover:bg-[#F4F7FA]'}`}>{tab.icon}{tab.label}</button>)}</nav></section>
    {meuViverMaisTab === 'visao_geral' && <Overview score={currentScore} navigateTo={navigateTo} />}
    {meuViverMaisTab === 'gdp' && <main className="space-y-6">
      <section className="rounded-3xl bg-[#163A63] p-6 text-white sm:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-center"><div><span className="text-xs font-black uppercase tracking-widest text-[#7CE2DB]">GDP • Gestão de Desempenho do Participante</span><h2 className="mt-2 text-2xl font-black sm:text-3xl">Meu Retrato e Evolução — GDP</h2><p className="mt-2 max-w-3xl text-sm leading-relaxed text-[#D9E4EE]">Sua evolução pessoal é a principal referência. As comparações servem apenas para contextualização, sem ranking ou julgamento.</p></div><div className="rounded-2xl bg-white/10 p-4 text-center"><span className="block text-xs text-[#B4EBE6]">IBPL atual</span><strong className="text-4xl">{formatPercentage(currentScore)}</strong><span className="block text-xs text-[#B4EBE6]">{date(surveyResult?.completedAt || (latestPoint?.date ?? '2026-08-25'))}</span></div></div><div className="mt-6 flex flex-wrap gap-2">{['Visão geral', 'Evolução', 'Pessoas como eu', 'Finanças', 'Saúde', 'Histórico e ações'].map((label) => <a key={label} href={`#gdp-${label.toLowerCase().replaceAll(' ', '-')}`} className="rounded-full border border-white/20 px-3 py-1.5 text-xs font-bold text-[#D9E4EE] hover:bg-white/10">{label}</a>)}</div></section>
      {!showDemo && realCount < 2 && <section className={`${card} p-6 sm:p-7`} id="gdp-visão-geral"><div className="flex items-start gap-4"><div className="rounded-2xl bg-[#E6F7F6] p-3 text-[#0A7D76]"><Sparkles className="h-6 w-6" /></div><div className="flex-1"><Pill>Seu ponto de partida</Pill><h2 className="mt-2 text-xl font-black text-[#163A63]">{surveyResult ? 'Seu ponto de partida' : 'Comece a construir seu histórico'}</h2><p className="mt-2 text-sm leading-relaxed text-[#5A6F82]">{surveyResult ? 'Esta é sua primeira avaliação. Nas próximas medições, você poderá acompanhar sua evolução e relacioná-la às ações realizadas.' : 'Realize sua primeira avaliação para começar a construir seu histórico. Nas próximas medições, você poderá acompanhar sua evolução e relacioná-la às ações realizadas.'}</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="IBPL inicial" value={formatPercentage(currentScore)} /><Metric label="Data da avaliação" value={surveyResult ? date(surveyResult.completedAt) : 'Ainda não realizada'} /><Metric label="Referência" value="A construir" /></div><button onClick={() => setShowDemo(true)} className="mt-5 rounded-xl bg-[#163A63] px-4 py-3 text-sm font-bold text-white">Visualizar exemplo demonstrativo de 5 anos <LineIcon className="inline h-4 w-4" /></button></div></div></section>}
      {showDemo && <div className="rounded-2xl border border-[#F0D58A] bg-[#FFF8E8] p-4 text-sm text-[#6D5920]"><Info className="mr-2 inline h-4 w-4" /> Cenário demonstrativo — os dados abaixo ilustram como seu histórico poderá ser apresentado.</div>}
      {realCount >= 2 || showDemo || realCount === 0 ? <>
        <section className={`${card} p-6`} id="gdp-evolução"><SectionTitle icon={<LineIcon />} title="Minha evolução" description="Histórico de até cinco anos com a mediana e a faixa mais frequente do grupo." /><div className="mt-4 flex flex-wrap gap-2" role="group" aria-label="Período do histórico">{(['1', '3', '5', 'all'] as const).map((item) => <button key={item} onClick={() => setPeriod(item)} className={`rounded-lg px-3 py-2 text-xs font-bold ${period === item ? 'bg-[#163A63] text-white' : 'bg-[#F4F7FA] text-[#5A6F82]'}`}>{item === 'all' ? 'Todo o histórico' : `${item} ano${item === '1' ? '' : 's'}`}</button>)}<select value={selectedPillar} onChange={(event) => setSelectedPillar(event.target.value as 'ibpl' | DimensionId)} aria-label="Indicador histórico" className="ml-auto rounded-lg border border-[#D9E4EE] bg-white px-3 py-2 text-xs font-bold text-[#163A63]"><option value="ibpl">IBPL geral</option>{DIMENSIONS.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="mt-5 h-72" aria-label="Gráfico de evolução do IBPL"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartData} margin={{ top: 12, right: 8, bottom: 4, left: -12 }}><CartesianGrid stroke="#EEF3F7" vertical={false} /><XAxis dataKey="year" tick={{ fontSize: 11 }} /><YAxis domain={[0, 100]} tick={{ fontSize: 11 }} /><Tooltip content={<HistoryTooltip />} /><Area type="monotone" dataKey="p75" stroke="none" fill="#B4EBE6" fillOpacity={0.35} name="Percentil 75" /><Area type="monotone" dataKey="p25" stroke="none" fill="#fff" fillOpacity={1} name="Percentil 25" /><Line type="monotone" dataKey="median" name="Mediana do grupo" stroke="#7B8FA3" strokeDasharray="5 5" dot={false} connectNulls /><Line type="monotone" dataKey="value" name={selectedPillar === 'ibpl' ? 'Meu IBPL' : labelFor(selectedPillar)} stroke="#0A988F" strokeWidth={3} dot={(props) => <circle {...props} r={6} fill="#163A63" stroke="#fff" strokeWidth={2} onClick={() => setSelectedPoint(chartHistory[props.index])} tabIndex={0} aria-label={`Avaliação de ${chartHistory[props.index]?.year}`} />} /></ComposedChart></ResponsiveContainer></div><div className="mt-3 flex flex-wrap gap-4 text-xs text-[#5A6F82]"><span><i className="mr-1 inline-block h-2 w-5 rounded bg-[#0A988F]" />Meu resultado</span><span><i className="mr-1 inline-block h-0.5 w-5 border-t-2 border-dashed border-[#7B8FA3]" />Mediana da referência</span><span><i className="mr-1 inline-block h-2 w-5 rounded bg-[#B4EBE6]" />Faixa mais frequente (P25–P75)</span></div><p className="mt-4 text-xs text-[#7F8C8D]">Clique em um ponto para consultar as ações e o contexto daquele período. {showDemo && 'Todos os valores desta visualização são demonstrativos.'}</p></section>
        <section className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]" id="gdp-pessoas-como-eu"><ReferenceSection available={referenceAvailable} text={groupText} /><PillarComparison scores={currentPillarScores} onSelect={setSelectedPillar} /></section>
        <FinancialSection comparisonView={comparisonView} setComparisonView={setComparisonView} navigateTo={navigateTo} />
        <HealthSection open={healthOpen} setOpen={setHealthOpen} navigateTo={navigateTo} />
        <HistorySection points={chartHistory} onSelect={setSelectedPoint} />
      </> : <EmptyState>Seu histórico real aparecerá automaticamente a partir da segunda avaliação. As avaliações anteriores não são sobrescritas.</EmptyState>}
    </main>}
    {meuViverMaisTab === 'pdp' && <PdpView myPlan={myPlan} navigateTo={navigateTo} />}
    {selectedPoint && <HistoryDialog point={selectedPoint} onClose={() => setSelectedPoint(null)} />}
  </div>;
};

const SectionTitle = ({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) => <div className="flex gap-3"><div className="mt-0.5 text-[#0A988F]">{icon}</div><div><h2 className="text-lg font-black text-[#163A63]">{title}</h2><p className="mt-1 text-xs text-[#5A6F82]">{description}</p></div></div>;
const Metric = ({ label, value }: { label: string; value: string }) => <div className="rounded-xl bg-[#F4F7FA] p-3"><span className="block text-[11px] text-[#5A6F82]">{label}</span><strong className="mt-1 block text-lg text-[#163A63]">{value}</strong></div>;
const HistoryTooltip = ({ active, payload, label }: any) => active && payload?.length ? <div className="rounded-xl border border-[#D9E4EE] bg-white p-3 text-xs shadow-lg"><strong className="block text-[#163A63]">{label}</strong>{payload.filter((p: any) => p.value !== undefined).map((p: any) => <div key={p.name} className="mt-1 flex justify-between gap-4"><span>{p.name}</span><b>{p.value}%</b></div>)}</div> : null;

const ReferenceSection = ({ available, text }: { available: boolean; text: string }) => <section className={`${card} p-6`}><SectionTitle icon={<Users />} title="Pessoas em contexto semelhante" description="Uma referência agregada para ajudar a interpretar seu contexto." />{available ? <><p className="mt-4 text-sm leading-relaxed text-[#5A6F82]">{text}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Metric label="Participantes" value={String(DEMO_REFERENCE_GROUP.participantCount)} /><Metric label="Período" value={DEMO_REFERENCE_GROUP.period} /><Metric label="Última atualização" value={DEMO_REFERENCE_GROUP.updatedAt} /><Metric label="Filtros aplicados" value="6 características" /></div><p className="mt-4 text-xs text-[#7F8C8D]">A comparação com a comunidade serve apenas para contextualização. Não exibimos pessoas individualmente.</p></> : <EmptyState>Ainda não há participantes suficientes para apresentar esta referência com segurança.</EmptyState>}</section>;

const PillarComparison = ({ scores, onSelect }: { scores: Record<DimensionId, number>; onSelect: (value: DimensionId) => void }) => { const data = DIMENSIONS.map((item) => ({ name: item.shortName, fullName: item.name, participant: scores[item.id], median: Math.round(scores[item.id] * 0.92) })); return <section className={`${card} p-6`}><SectionTitle icon={<BarChart3 />} title="Comparativo por pilares" description="Resultado pessoal e mediana da referência, sem ranking." /><div className="mt-4 h-80"><ResponsiveContainer width="100%" height="100%"><Bar data={data} layout="vertical" margin={{ left: 12, right: 8 }}><XAxis type="number" domain={[0, 100]} hide /><YAxis type="category" dataKey="name" tick={{ fontSize: 10 }} width={70} /><Tooltip formatter={(value: number, name: string) => [`${value}%`, name === 'participant' ? 'Meu resultado' : 'Mediana da referência']} /><Bar dataKey="median" name="Mediana da referência" fill="#AEBECD" barSize={12} radius={[0, 5, 5, 0]} /><Bar dataKey="participant" name="Meu resultado" fill="#12B8AE" barSize={12} radius={[0, 5, 5, 0]} onClick={(item) => onSelect(DIMENSIONS.find((d) => d.shortName === item.name)?.id ?? 'saude_fisica')} /></Bar></ResponsiveContainer></div><div className="space-y-2">{data.slice(0, 3).map((item) => <button key={item.name} onClick={() => onSelect(DIMENSIONS.find((d) => d.shortName === item.name)?.id ?? 'saude_fisica')} className="flex w-full items-center justify-between rounded-xl bg-[#F4F7FA] p-2 text-left text-xs"><span>{item.fullName}</span><Pill tone={item.participant > item.median + 5 ? 'teal' : 'blue'}>{item.participant > item.median + 5 ? 'Fortaleza atual' : statusFor(item.participant, item.median, item.median - 8, item.median + 8)}</Pill></button>)}</div></section>; };

const FinancialSection = ({ comparisonView, setComparisonView, navigateTo }: { comparisonView: 'participant' | 'cohort' | 'community'; setComparisonView: (v: 'participant' | 'cohort' | 'community') => void; navigateTo: any }) => <section className={`${card} p-6`} id="gdp-finanças"><SectionTitle icon={<BarChart3 />} title="Minha visão financeira" description="Percentuais do orçamento, sem valores individuais de outras pessoas." /><div className="mt-4 flex flex-wrap gap-2">{[['participant', 'Minha visão'], ['cohort', 'Pessoas como eu'], ['community', 'Comunidade PREVI']].map(([id, label]) => <button key={id} onClick={() => setComparisonView(id as any)} className={`rounded-lg px-3 py-2 text-xs font-bold ${comparisonView === id ? 'bg-[#163A63] text-white' : 'bg-[#F4F7FA] text-[#5A6F82]'}`}>{label}</button>)}</div><div className="mt-5 space-y-3">{DEMO_FINANCIAL_COMPOSITION.map((row) => <div key={row.category}><div className="mb-1 flex justify-between text-xs"><span>{row.category}</span><b>{row[comparisonView]}%</b></div><div className="h-3 overflow-hidden rounded-full bg-[#EEF3F7]"><div className={`h-full rounded-full ${comparisonView === 'participant' ? 'bg-[#12B8AE]' : comparisonView === 'cohort' ? 'bg-[#7B8FA3]' : 'bg-[#163A63]'}`} style={{ width: `${row[comparisonView]}%` }} /></div></div>)}</div><div className="mt-6 grid gap-3 md:grid-cols-3"><Metric label="Gastos essenciais" value="40%" /><Metric label="Saúde" value="21% · ref. 14%" /><Metric label="Reservas" value="9% · ref. 10%" /></div><p className="mt-4 text-xs leading-relaxed text-[#5A6F82]">Na sua referência, os gastos com saúde representam uma mediana de 14% do orçamento. No contexto informado por você, representam 21%. Essa diferença não indica inadequação, mas pode ser considerada no seu planejamento.</p><button onClick={() => navigateTo('meu_viver_mais', 'pdp', 'recursos_financeiros')} className="mt-4 rounded-xl bg-[#E6F7F6] px-4 py-3 text-sm font-bold text-[#0A7D76]">Usar esta informação no meu PDP <ArrowRight className="inline h-4 w-4" /></button></section>;

const HealthSection = ({ open, setOpen, navigateTo }: { open: boolean; setOpen: (v: boolean) => void; navigateTo: any }) => <section className={`${card} p-6`} id="gdp-saúde"><SectionTitle icon={<HeartPulse />} title="Minha saúde e prevenção" description="Indicadores de autocuidado, sem nota médica ou diagnóstico." /><div className="mt-5 grid gap-4 md:grid-cols-2">{DEMO_HEALTH_INDICATORS.map((item) => <div key={item.label} className="rounded-2xl bg-[#F4F7FA] p-4"><div className="flex justify-between gap-3 text-sm font-bold text-[#163A63]"><span>{item.label}</span><span className="text-[#0A7D76]">{item.participant}{item.unit === '%' ? '%' : ` ${item.unit}`}</span></div><div className="relative mt-3 h-2 rounded-full bg-[#D9E4EE]"><div className="h-full rounded-full bg-[#12B8AE]" style={{ width: `${item.unit === '%' ? item.participant : item.participant * 20}%` }} /><span className="absolute top-[-3px] h-4 w-0.5 bg-[#7B8FA3]" style={{ left: `${item.unit === '%' ? item.median : item.median * 20}%` }} /></div><p className="mt-2 text-[11px] text-[#5A6F82]">Mediana: {item.median}{item.unit === '%' ? '%' : ` ${item.unit}`} · faixa mais frequente: {item.p25}–{item.p75}</p></div>)}</div><button onClick={() => setOpen(!open)} className="mt-5 text-sm font-bold text-[#0A7D76]">{open ? 'Ocultar cuidados preventivos' : 'Cuidados preventivos para conversar com sua equipe de saúde'} <ChevronDown className="inline h-4 w-4" /></button>{open && <div className="mt-4 rounded-2xl border border-[#D9E4EE] p-4 text-sm text-[#5A6F82]"><p><CheckCircle2 className="mr-2 inline h-4 w-4 text-[#0A7D76]" />Realizados: acompanhamento de saúde informado.</p><p className="mt-2"><CircleHelp className="mr-2 inline h-4 w-4 text-[#7B8FA3]" />Pendentes ou não informados: converse com sua equipe de saúde sobre o que faz sentido para você.</p><p className="mt-3 text-xs">Esta funcionalidade depende de autorização do participante e de integração institucional com a CASSI. Os indicadores deste protótipo são demonstrativos.</p></div>}<button onClick={() => navigateTo('meu_viver_mais', 'pdp', 'saude_emocional')} className="mt-4 rounded-xl bg-[#E6F7F6] px-4 py-3 text-sm font-bold text-[#0A7D76]">Usar esta informação no meu PDP <ArrowRight className="inline h-4 w-4" /></button></section>;

const HistorySection = ({ points, onSelect }: { points: GdpHistoryPoint[]; onSelect: (point: GdpHistoryPoint) => void }) => <section className={`${card} p-6`} id="gdp-histórico-e-ações"><SectionTitle icon={<Calendar />} title="Meu histórico detalhado" description="Selecione um período para relacionar ações e momentos, sem presumir causa e efeito." /><div className="mt-5 grid gap-3 md:grid-cols-5">{points.map((point) => <button key={point.id} onClick={() => onSelect(point)} className="rounded-2xl border border-[#D9E4EE] p-4 text-left transition hover:border-[#12B8AE] hover:bg-[#F8FCFC]"><span className="text-xs font-bold text-[#0A7D76]">{point.year}</span><strong className="mt-1 block text-2xl text-[#163A63]">{point.personal}%</strong><span className="mt-2 block text-xs text-[#5A6F82]">{point.actionsStarted.length + point.actionsCompleted.length} ações registradas</span></button>)}</div><p className="mt-5 rounded-xl bg-[#F4F7FA] p-3 text-xs leading-relaxed text-[#5A6F82]"><Info className="mr-1 inline h-4 w-4" />As ações ocorreram entre as avaliações e podem ter contribuído para as mudanças observadas. O gráfico não estabelece relação automática de causa e efeito.</p></section>;

const HistoryDialog = ({ point, onClose }: { point: GdpHistoryPoint; onClose: () => void }) => <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#163A63]/60 p-0 sm:items-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="history-dialog-title"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white p-6 sm:rounded-3xl sm:p-8"><div className="flex items-start justify-between gap-4"><div><Pill>Período demonstrativo</Pill><h2 id="history-dialog-title" className="mt-2 text-2xl font-black text-[#163A63]">{point.year} · IBPL {point.personal}%</h2><p className="mt-1 text-sm text-[#5A6F82]">Avaliação em {date(point.date)}</p></div><button onClick={onClose} aria-label="Fechar detalhes" className="rounded-full p-2 hover:bg-[#F4F7FA]"><X /></button></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Detail title="Variação desde a medição anterior" value={point.year === 2022 ? 'Primeira avaliação' : `+${point.personal - DEMO_GDP_HISTORY.find((item) => item.year === point.year - 1)!.personal} pontos`} /><Detail title="Fortalezas identificadas" value={point.strengths.join(', ')} /><Detail title="Oportunidades prioritárias" value={point.opportunities.join(', ')} /><Detail title="Momentos de vida" value={point.lifeMoments.join(', ')} /><Detail title="Ações iniciadas" value={point.actionsStarted.join('; ') || 'Nenhuma registrada'} /><Detail title="Ações concluídas" value={point.actionsCompleted.join('; ') || 'Nenhuma registrada'} /><Detail title="Programas" value={point.programs.join(', ') || 'Nenhum registrado'} /><Detail title="Observações pessoais" value={point.notes} /></div><p className="mt-6 rounded-xl bg-[#FFF8E8] p-3 text-xs leading-relaxed text-[#6D5920]">As ações ocorreram entre as avaliações e podem ter contribuído para as mudanças observadas. O gráfico não estabelece relação automática de causa e efeito.</p></div></div>;
const Detail = ({ title, value }: { title: string; value: string }) => <div><span className="text-[11px] font-bold uppercase tracking-wide text-[#7B8FA3]">{title}</span><p className="mt-1 text-sm text-[#163A63]">{value}</p></div>;

const Overview = ({ score, navigateTo }: { score: number; navigateTo: any }) => <div className="space-y-6"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="IBPL atual" value={formatPercentage(score)} /><Metric label="Última avaliação" value="25/08/2026" /><Metric label="Ações em andamento" value="2" /><Metric label="PDP concluído" value="65%" /></div><section className="rounded-3xl bg-[#163A63] p-6 text-white"><h2 className="text-xl font-black">Seu momento em uma frase</h2><p className="mt-2 text-sm leading-relaxed text-[#D9E4EE]">Sua evolução pessoal é a principal referência. O GDP ajuda você a escolher próximos passos que façam sentido para o seu momento.</p><Pill>Dados demonstrativos</Pill></section><div className="grid gap-6 lg:grid-cols-2"><section className={`${card} p-6`}><h2 className="text-lg font-black text-[#163A63]">Principais fortalezas</h2><div className="mt-4 space-y-2"><div className="rounded-xl bg-[#E6F7F6] p-3 text-sm font-bold text-[#0A7D76]">Relacionamentos · 88%</div><div className="rounded-xl bg-[#E6F7F6] p-3 text-sm font-bold text-[#0A7D76]">Saúde física · 82%</div></div></section><section className={`${card} p-6`}><h2 className="text-lg font-black text-[#163A63]">Oportunidades prioritárias</h2><p className="mt-2 text-sm text-[#5A6F82]">Saúde emocional e Propósito podem orientar novos passos no PDP.</p><button onClick={() => navigateTo('meu_viver_mais', 'gdp')} className="mt-4 text-sm font-bold text-[#0A7D76]">Ver meu retrato e evolução <ArrowRight className="inline h-4 w-4" /></button></section></div></div>;

const PdpView = ({ myPlan, navigateTo }: { myPlan: any[]; navigateTo: any }) => <div className="space-y-6"><section className="rounded-3xl bg-gradient-to-r from-[#163A63] to-[#1E466F] p-6 text-white sm:p-8"><span className="text-xs font-black uppercase tracking-widest text-[#7CE2DB]">PDP • Plano de Desenvolvimento do Participante</span><h2 className="mt-2 text-2xl font-black">Meu Plano de Desenvolvimento — PDP</h2><p className="mt-2 text-[#D9E4EE]">O GDP mostra como estou. O PDP me ajuda a decidir o que fazer.</p></section><section className={`${card} p-6`}><h2 className="text-lg font-black text-[#163A63]">Ações relacionadas ao meu contexto</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-2xl bg-[#FFF8E8] p-4"><Target className="text-[#0A7D76]" /><b className="mt-2 block">Saúde emocional</b><p className="mt-1 text-xs text-[#5A6F82]">Ação planejada para o novo ciclo.</p></div><div className="rounded-2xl bg-[#F4F7FA] p-4"><Sparkles className="text-[#0A7D76]" /><b className="mt-2 block">Propósito</b><p className="mt-1 text-xs text-[#5A6F82]">Conheça experiências que podem apoiar seu objetivo.</p></div><div className="rounded-2xl bg-[#F4F7FA] p-4"><Plus className="text-[#0A7D76]" /><b className="mt-2 block">Adicionar ação</b><p className="mt-1 text-xs text-[#5A6F82]">Escolha um próximo passo no seu ritmo.</p></div></div><button onClick={() => navigateTo('explorar')} className="mt-5 rounded-xl bg-[#163A63] px-4 py-3 text-sm font-bold text-white">Explorar experiências <ArrowRight className="inline h-4 w-4" /></button><p className="mt-4 text-xs text-[#7F8C8D]">{myPlan.length ? `${myPlan.length} experiência(s) já salva(s) no seu plano.` : 'Você ainda pode salvar experiências para acompanhar no seu plano.'}</p></section></div>;
