import React from 'react';
import { Activity, BookOpen, Compass, ArrowRight, Info } from 'lucide-react';
import { useApp, MeuViverMaisTab } from '../context/AppContext';
import { IBPL_HISTORY } from '../mock/ibplHistory';
import { CurrentIBPLRadar } from '../components/meu-viver-mais/CurrentIBPLRadar';
import { StrengthsAndOpportunities } from '../components/meu-viver-mais/StrengthsAndOpportunities';
import { InspirationsForMyMoment } from '../components/meu-viver-mais/InspirationsForMyMoment';
import { DevelopmentTrails } from '../components/meu-viver-mais/DevelopmentTrails';
import { Logbook } from '../components/meu-viver-mais/Logbook';
import { WhatsAppFollowupDemo } from '../components/meu-viver-mais/WhatsAppFollowupDemo';
import { FinancialAgeReference } from '../components/meu-viver-mais/FinancialAgeReference';
import { HealthAgeReference } from '../components/meu-viver-mais/HealthAgeReference';

const tabs: { id: MeuViverMaisTab; label: string; icon: React.ReactNode }[] = [
  { id: 'retrato', label: 'Meu Retrato e Evolução', icon: <Activity className="h-5 w-5" /> },
  { id: 'trilhas', label: 'Trilhas de Desenvolvimento', icon: <Compass className="h-5 w-5" /> },
  { id: 'diario', label: 'Diário de Bordo', icon: <BookOpen className="h-5 w-5" /> },
];

export const MeuViverMaisView: React.FC = () => {
  const { currentParticipant, surveyResult, meuViverMaisTab, setMeuViverMaisTab, navigateTo } = useApp();
  const current = surveyResult?.ibplScore ?? IBPL_HISTORY.at(-1)?.ibpl ?? 76;
  const scores = IBPL_HISTORY.at(-1)?.scores ?? [];
  return <div className="mx-auto w-full max-w-7xl space-y-6 px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <section className="rounded-3xl border border-[#D9E4EE] bg-white p-5 shadow-sm sm:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div><span className="text-sm font-black uppercase tracking-widest text-[#0A7D76]">Área pessoal</span><h1 className="mt-2 text-3xl font-black text-[#163A63]">Meu Viver Mais</h1><p className="mt-2 text-lg text-[#5A6F82]">Acompanhe seu momento, suas escolhas e sua evolução.</p></div>{!surveyResult&&<button onClick={()=>navigateTo('questionario_intro')} className="min-h-12 rounded-xl bg-[#163A63] px-4 text-base font-bold text-white">Começar minha avaliação <ArrowRight className="inline h-5 w-5"/></button>}</div><nav aria-label="Navegação do Meu Viver Mais" className="mt-6 grid gap-2 border-t border-[#EEF3F7] pt-4 md:grid-cols-3">{tabs.map(tab=><button key={tab.id} onClick={()=>setMeuViverMaisTab(tab.id)} aria-current={meuViverMaisTab===tab.id?'page':undefined} className={`flex min-h-14 items-center justify-center gap-2 rounded-xl px-3 text-base font-bold focus-visible:outline focus-visible:outline-4 focus-visible:outline-[#F2B84B] ${meuViverMaisTab===tab.id?'bg-[#163A63] text-white':'text-[#5A6F82] hover:bg-[#F4F7FA]'}`}>{tab.icon}{tab.label}</button>)}</nav></section>
    {meuViverMaisTab==='retrato'&&<main className="space-y-6"><section className="rounded-3xl bg-[#163A63] p-5 text-white shadow-sm sm:p-8"><div className="grid gap-5 lg:grid-cols-[1.4fr_.8fr]"><div><span className="text-sm font-bold uppercase tracking-widest text-[#B4EBE6]">Seu momento atual · demonstrativo</span><h2 className="mt-3 text-2xl font-black sm:text-3xl">Olá, {currentParticipant.name}. Seu retrato mostra um momento de fortalecimento dos relacionamentos e uma oportunidade de dedicar mais atenção ao equilíbrio emocional.</h2><p className="mt-3 text-base leading-relaxed text-[#D9E4EE]">Estas informações vêm das respostas e registros que você escolheu compartilhar. Elas apoiam sua reflexão e não são um diagnóstico.</p><button onClick={()=>alert('O IBPL é uma síntese demonstrativa das suas respostas de avaliação. Ele não define quem você é e não deve ser interpretado isoladamente.')} className="mt-5 min-h-12 rounded-xl bg-white px-4 text-base font-bold text-[#163A63]">Entenda seu resultado</button></div><div className="rounded-2xl bg-white/10 p-5"><span className="text-base text-[#B4EBE6]">IBPL atual</span><strong className="mt-1 block text-5xl">{current}%</strong><p className="mt-2 text-base text-[#D9E4EE]">+4% em relação à avaliação anterior</p><p className="mt-3 text-sm text-[#D9E4EE]">Última avaliação: 25/08/2026<br/>Evolução registrada no histórico de avaliações</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2"><div className="rounded-2xl bg-white/10 p-4"><b className="text-[#B4EBE6]">Duas fortalezas</b><p className="mt-2 text-base">Relacionamentos · Saúde Emocional</p></div><div className="rounded-2xl bg-white/10 p-4"><b className="text-[#B4EBE6]">Próximos passos possíveis</b><p className="mt-2 text-base">Cuidar do equilíbrio emocional · Organizar projetos · Pedir apoio</p></div></div></section><p className="rounded-2xl border border-[#F0D58A] bg-[#FFF8E8] p-4 text-base text-[#6D5920]"><Info className="mr-2 inline h-5 w-5"/>Por que estou vendo isso? O resumo considera respostas da avaliação e registros demonstrativos.</p><CurrentIBPLRadar scores={scores}/><StrengthsAndOpportunities/><FinancialAgeReference/><HealthAgeReference/><InspirationsForMyMoment/><section className="rounded-3xl border border-[#D9E4EE] bg-white p-5 shadow-sm sm:p-7"><h2 className="text-xl font-black text-[#163A63]">Resumo das atividades e cursos em andamento</h2><p className="mt-2 text-base text-[#5A6F82]">Você tem 2 atividades demonstrativas em andamento. Acesse Trilhas de Desenvolvimento para continuar.</p><button onClick={()=>setMeuViverMaisTab('trilhas')} className="mt-4 min-h-12 rounded-xl bg-[#163A63] px-4 text-base font-bold text-white">Ver minhas atividades</button></section><WhatsAppFollowupDemo/></main>}
    {meuViverMaisTab==='trilhas'&&<DevelopmentTrails/>}{meuViverMaisTab==='diario'&&<Logbook participantId={currentParticipant.id}/>}</div>;
};
