import React, { useState } from 'react';
import { JournalEntry } from '../../types';
import { LOGBOOK_ENTRIES } from '../../mock/logbookEntries';
import { loadJournal, saveJournal } from '../../services/meuViverMaisStorage';

type Step = 'good' | 'better' | 'review';
export const Logbook: React.FC<{ participantId: string }> = ({ participantId }) => {
  const [entries, setEntries] = useState<JournalEntry[]>(() => loadJournal(participantId, LOGBOOK_ENTRIES));
  const [collecting, setCollecting] = useState(false);
  const [historyOpen, setHistoryOpen] = useState(false);
  const [step, setStep] = useState<Step>('good');
  const [good, setGood] = useState('');
  const [better, setBetter] = useState('');
  const [saved, setSaved] = useState(false);
  const begin = () => { setCollecting(true); setHistoryOpen(false); setSaved(false); setStep('good'); };
  const cancel = () => { setCollecting(false); setGood(''); setBetter(''); setStep('good'); };
  const save = () => { const entry: JournalEntry = { id: `journal-${Date.now()}`, participantId, date: new Date().toISOString().slice(0, 10), type: 'conquista', text: [good, better].filter(Boolean).join(' · '), whatWasGood: good, whatCouldImprove: better, privacy: 'privado', source: 'registro' }; const next = [entry, ...entries]; setEntries(next); saveJournal(participantId, next); setSaved(true); setCollecting(false); setGood(''); setBetter(''); setStep('good'); };
  const formatDate = (value: string) => new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR');
  return <main className="space-y-5 text-[18px]">
    <section className="rounded-3xl bg-[#163A63] p-5 text-white shadow-sm sm:p-7"><p className="text-base font-bold uppercase tracking-wider text-[#B4EBE6]">Diário pessoal do seu ciclo</p><h2 className="mt-2 text-2xl font-black">Diário de Bordo</h2><p className="mt-2 text-lg text-[#D9E4EE]">Registre avanços e aprendizados no seu ritmo.</p><div className="mt-5 flex flex-col gap-3 sm:flex-row"><button onClick={begin} className="min-h-12 rounded-xl bg-white px-4 text-lg font-bold text-[#163A63]">Registrar como estou</button><button onClick={() => setHistoryOpen(true)} className="min-h-12 rounded-xl border border-white/40 px-4 text-lg font-bold">Ver meu histórico</button></div></section>
    {saved && <p role="status" className="rounded-2xl border border-[#B4EBE6] bg-[#E6F7F6] p-4 font-bold text-[#0A7D76]">Seu registro foi salvo.</p>}
    {collecting && <section className="rounded-3xl border border-[#D9E4EE] bg-white p-5 shadow-sm sm:p-7" aria-labelledby="registro-title"><div className="max-w-[800px]"><h2 id="registro-title" className="text-xl font-black text-[#163A63]">Vamos registrar como você está</h2>{step !== 'review' && <><p className="mt-3 text-base font-bold text-[#0A7D76]">Pergunta {step === 'good' ? '1' : '2'} de 2</p><label htmlFor="journal-answer" className="mt-2 block text-xl font-bold">{step === 'good' ? 'O que foi bom desde o seu último registro?' : 'O que poderia ter sido melhor?'}</label><textarea id="journal-answer" autoFocus value={step === 'good' ? good : better} onChange={e => step === 'good' ? setGood(e.target.value) : setBetter(e.target.value)} className="mt-4 min-h-36 w-full rounded-xl border border-[#B9CAD8] p-4 text-[18px] leading-relaxed" placeholder="Você pode responder com poucas palavras ou escrever mais, se quiser."/><div className="mt-4 flex flex-col-reverse gap-3 sm:flex-row sm:justify-between"><button onClick={() => step === 'good' ? cancel() : setStep('good')} className="min-h-12 rounded-xl border px-5 text-lg font-bold">{step === 'good' ? 'Cancelar' : 'Voltar'}</button><button onClick={() => step === 'good' ? setStep('better') : setStep('review')} className="min-h-12 rounded-xl bg-[#163A63] px-5 text-lg font-bold text-white">Continuar</button></div></>}{step === 'review' && <><p className="mt-4 text-xl font-bold">Revise suas respostas</p><div className="mt-4 space-y-4"><div className="rounded-2xl bg-[#F4F7FA] p-4"><b>O que foi bom</b><p className="mt-2 whitespace-pre-wrap">{good || 'Você preferiu não registrar este ponto.'}</p></div><div className="rounded-2xl bg-[#F4F7FA] p-4"><b>O que pode ser melhorado</b><p className="mt-2 whitespace-pre-wrap">{better || 'Você preferiu não registrar este ponto.'}</p></div></div><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><button onClick={() => setStep('good')} className="min-h-12 rounded-xl border px-5 text-lg font-bold">Editar respostas</button><button onClick={save} className="min-h-12 rounded-xl bg-[#163A63] px-5 text-lg font-bold text-white">Salvar no Diário de Bordo</button><button onClick={cancel} className="min-h-12 rounded-xl border px-5 text-lg font-bold">Cancelar</button></div></>}</div></section>}
    {historyOpen && <section id="historico" className="rounded-3xl border border-[#D9E4EE] bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-black text-[#163A63]">Histórico do meu ciclo</h2><p className="mt-1 text-base text-[#5A6F82]">Registros em ordem cronológica inversa.</p></div><button onClick={() => setHistoryOpen(false)} className="min-h-12 rounded-xl border px-4 text-lg font-bold">Fechar histórico</button></div>{!entries.length ? <p className="mt-4 rounded-2xl bg-[#F4F7FA] p-4">Seu Diário de Bordo ainda não tem registros. Quando quiser, registre como está.</p> : <div className="mt-4 space-y-3">{entries.map((entry) => <details key={entry.id} className="rounded-2xl border border-[#EEF3F7] bg-[#F4F7FA] p-4"><summary className="cursor-pointer text-lg font-bold">{formatDate(entry.date)}</summary><div className="mt-4 space-y-3"><div><b>O que foi bom</b><p className="mt-1 whitespace-pre-wrap">{entry.whatWasGood || entry.text}</p></div><div><b>O que pode ser melhorado</b><p className="mt-1 whitespace-pre-wrap">{entry.whatCouldImprove || 'Não informado.'}</p></div><button onClick={() => { if (confirm('Excluir este registro?')) { const next = entries.filter(item => item.id !== entry.id); setEntries(next); saveJournal(participantId, next); } }} className="min-h-12 text-base font-bold text-[#A33B63]">Excluir registro</button></div></details>)}</div>}</section>}
  </main>;
};
